import Header from "@/components/Header/Header";
import type { Metadata } from "next";
import "./globals.css"
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "BookStore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
